version: "3"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger-all-in-one
  # Database
  mysql-db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'groot'
      MYSQL_PASSWORD: 'groot'
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./setup:/docker-entrypoint-initdb.d
volumes:
  my-db:
